---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: kiran07021998/spring-boot-mongo # Public Docker Hub image
        name: springboot
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
